providers = ['node', 'java', 'python']

[phases.setup]
nixPkgs = [
  "...",
  "ffmpeg_6-full",
  "imagemagick",
  "gmic",
  "gtk3",
  "nspr",
  "nss",
  "libx11",
  "libxcomposite",
  "libxcursor",
  "libxdamage",
  "libxfixes",
  "libxi",
  "libxrandr",
  "libxss",
  "libxtst",
  "xdg-utils"
]

[phases.build]
cmds = ['chmod -R 754 /app/bin/* /app/lib/*', 'cp -R /app/bin/linux/* /usr/bin']
