providers = ['node', 'java', 'python']

[phases.setup]
nixPkgs = [
  "...",
  "ffmpeg_6-full",
  "imagemagick",
  "gmic",
  "gtk3",
  "nspr",
  "nss",
  "xorg.libX11",
  "xorg.libXcomposite",
  "xorg.libXcursor",
  "xorg.libXdamage",
  "xorg.libXfixes",
  "xorg.libXi",
  "xorg.libXrandr",
  "xorg.libXtst",
  "xdg-utils"
]

[phases.build]
cmds = ['chmod -R 754 /app/bin/* /app/lib/*', 'cp -R /app/bin/linux/* /usr/bin']
